name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build React App
        run: |
          cd react-app && npm install && npm run build

      - name: Build Svelte App
        run: |
          cd svelte-app && npm install && npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: me-central-1

      - name: Deploy Frontend
        run: |
          aws s3 sync react-app/build s3://frontend-react-app-bucket
          aws s3 sync svelte-app/build s3://frontend-svelte-app-bucket
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

      - name: Deploy Backend
        run: |
          aws ecs update-service --cluster api-cluster --service api-service --force-new-deployment

  rollback:
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: me-central-1

      - name: Rollback Frontend
        run: |
          echo "Rolling back React frontend to previous deployment..."
          aws s3 cp s3://frontend-react-app-bucket-backup s3://frontend-react-app-bucket --recursive
          echo "Rolling back Svelte frontend to previous deployment..."
          aws s3 cp s3://frontend-svelte-app-bucket-backup s3://frontend-svelte-app-bucket --recursive
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

      - name: Rollback Backend
        run: |
          echo "Rolling back backend ECS service..."
          aws ecs update-service --cluster api-cluster --service api-service --force-new-deployment --rollback